xcopy c:\hprojects\scripting\engines\beanshell\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\beanshell\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\browserjs\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\browserjs\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\ejs\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\ejs\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\freemarker\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\freemarker\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\groovy\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\groovy\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jacl\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jacl\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jaskell\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jaskell\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\java\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\java\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\javascript\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\javascript\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jawk\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jawk\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jelly\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jelly\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jep\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jep\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jexl\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jexl\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jruby\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jruby\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jst\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jst\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\judo\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\judo\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\juel\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\juel\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jython\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\jython\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\ognl\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\ognl\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\pnuts\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\pnuts\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\scheme\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\scheme\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\velocity\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\velocity\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\xpath\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\xpath\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\xslt\build\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
xcopy c:\hprojects\scripting\engines\xslt\lib\*.jar c:\hprojects\jzab\plugins\scripting\target\ /Y
